# Generated by Django 4.2.6 on 2023-10-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'CEO'), (1, 'Staff'), (2, 'Buyer')], default=2),
        ),
    ]
