# Generated by Django 4.2.6 on 2023-10-30 15:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=blog.models.image_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
