# Generated by Django 4.2.6 on 2023-10-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
