# Generated by Django 4.2.6 on 2023-12-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
