# Generated by Django 4.2.6 on 2023-12-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_shop_category_alter_shop_image_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_sale',
        ),
    ]
